#Getting Started with Tensor flow
Let's stay consistent on this journey

#Objectives

1. Build a neural network
2. Train this neural network
3. Evaluate and predict


In [1]:
import tensorflow as tf

In [15]:
import numpy as np

In [2]:
#Load and prep data
mnist = tf.keras.datasets.mnist

(X_train, y_train), (X_test, y_test) = mnist.load_data()

#convert the samples from integers to floating-point numbers
X_train, X_test = X_train / 255.0, X_test / 255.0

11493376/11490434 [==============================] - 0s 0us/step


In [14]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Dropout,Softmax

In [13]:
#Building the neural network

model = Sequential()

model.add(Flatten(input_shape =(28,28)))
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(10))

#log-odds
The model returns a vector of log odds

log-odds -> ln(odds) -> ln(P/(1-P))

odds = P/(1-P) Ex: .9/.1 = 9

Ex: ln(9) = 2.2

log-odds are inverse of sigmoid function



In [23]:
predictions = model(X_train[:1]).numpy()
predictions

array([[ 0.1474965 ,  0.25172302, -0.13217036,  0.00477463,  0.29332733,
         0.1163016 , -0.2721662 ,  0.12885517, -0.22061607,  0.17355683]],
      dtype=float32)

In [24]:
#Converting the lod-odds to probabilities
tf.nn.softmax(predictions).numpy

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[0.1085021 , 0.12042125, 0.08203144, 0.0940708 , 0.12553698,
        0.10516964, 0.07131501, 0.10649821, 0.07508772, 0.11136687]],
      dtype=float32)>>

In [25]:
#Caluclating the losses
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

#loss = -log(Trueclass)
Ex: -log(1/10) ~= 2.3


In [26]:
loss_fn(y_train[:1], predictions).numpy()
#This should be approx 2.3

2.2521808

In [27]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [28]:
#Training data
model.fit(X_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.2951 - accuracy: 0.9134
Epoch 2/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1403 - accuracy: 0.9588
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1087 - accuracy: 0.9670
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0893 - accuracy: 0.9727
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0726 - accuracy: 0.9775


In [29]:
#Predicting the data
model.evaluate(X_test,y_test, verbose=2)

313/313 - 0s - loss: 0.0791 - accuracy: 0.9762


[0.07913537323474884, 0.9761999845504761]

In [32]:
#Proability model
proability_model = Sequential([model, Softmax()])

In [33]:
#Raw predictions
proability_model(X_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[6.0885860e-08, 9.8295899e-11, 3.8940627e-07, 3.4661080e-05,
        3.4663006e-12, 2.0239977e-08, 8.3417028e-16, 9.9996424e-01,
        3.3903032e-07, 2.4586052e-07],
       [6.1398766e-09, 5.0184721e-05, 9.9994600e-01, 1.0202409e-06,
        1.0079046e-14, 1.4187829e-06, 4.0372054e-08, 3.0701343e-14,
        1.4575833e-06, 1.6818183e-12],
       [2.7517018e-07, 9.9964416e-01, 7.6041877e-05, 3.0083920e-06,
        2.8650771e-05, 3.0296517e-06, 1.8980669e-05, 1.7647752e-04,
        4.7949907e-05, 1.5377560e-06],
       [9.9932718e-01, 2.3641945e-08, 2.9301254e-05, 3.2869705e-06,
        6.0806287e-06, 3.0660792e-04, 1.6321083e-05, 4.5660207e-05,
        1.9754765e-05, 2.4581907e-04],
       [1.0019280e-07, 5.9462046e-10, 2.5729886e-07, 1.3355086e-07,
        9.9827480e-01, 5.3405614e-07, 1.8806533e-07, 1.5813576e-04,
        1.9668988e-07, 1.5656695e-03]], dtype=float32)>